POST  http://localhost:3001/auth/register
Content-Type: application/json

{
    "email": "messithanh2k@gmail.com",
    "password": "messithanh"
}

###

POST  http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "20180001@sis.hust.edu.vn",
    "password": "20180001",
    "role": "student"
}

###
POST  http://localhost:3001/auth/register
Content-Type: application/json

{
    "email": "nhathai.nguyen@sis.hust.edu.vn",
    "password": "nhathai123",
    "role": "lecturer"
}

###

POST http://localhost:3001/student/create
Content-Type: application/json

{
    "FullName": "Nguyen van C",
    "DateOfBirth": "2000-12-12",
    "SchoolYear": 63,
    "Class": "sa",
    "Sex": "Male", 
    "Major": "IT1",
    "Born": "Luong son, hoa binh",
    "IdentityNumber": "17896488",
    "PhoneNumber": "151564856413"
}

###

GET http://localhost:3001/student/11486488
Content-Type: application/json

###


DELETE http://localhost:3001/student/20180012
Content-Type: application/json

###
DELETE http://localhost:3001/auth/delete/20180000@sis.hust.edu.vn
Content-Type: application/json

###
POST http://localhost:3001/student/update
Content-Type: application/json

{
    "SID": "20180002",
    "FullName": "Nguyen van C",
    "DateOfBirth": "2000-12-12",
    "SchoolYear": 63,
    "Class": "01" ,
    "Sex": "Male", 
    "Major": "IT1",
    "Born": "Luong son, hoa binh",
    "IdentityNumber": "114896488",
    "PhoneNumber": "151564856413"
}
###
GET http://localhost:3001/subject/
Content-Type: application/json

###

POST http://localhost:3001/subject/create
Content-Type: application/json

{
    "SubID": "it033",
    "SubName": "avav",
    "Department": "bb",
    "Credit": 2
  
}

###
POST http://localhost:3001/lecturer/create
Content-Type: application/json

{
    "FullName": "Nguyễn Nhất Hải",
    "DateOfBirth": "1989-01-01",
    "Sex": "Male",
    "Born": "Hà Nội",
    "IdentityNumber": "187900111",
    "PhoneNumber": "0330000000"
}
###

GET http://localhost:3001/subject/getStudent/20180001
Content-Type: application/json

###
GET http://localhost:3001/lecturer/
Content-Type: application/json


###

POST http://localhost:3001/lecturer/create
Content-Type: application/json

{
    "FullName": "Nguyễn Mạnh Thắng",
    "DateOfBirth": "1988-12-12",
    "Sex": "Male", 
    "Born": "Luong son, hoa binh",
    "IdentityNumber": "177896588",
    "PhoneNumber": "151564856413"
}

###

POST http://localhost:3001/student/getclassdetail
Content-Type: application/json

{
    "ClassID": "12784"
}

###

POST http://localhost:3001/student/registerclass
Content-Type: application/json

{
    "email": "trung.vh180003@sis.hust.edu.vn",
    "classes": [12784, 12785]
}

###

POST http://localhost:3001/class/create
Content-Type: application/json

{
    "ClassID": "it01",
    "SubID": "it012",
    "LecID": "DoBaLam",
    "Day": "monday",
    "Room": "D307" ,
    "StartTime": 6, 
    "EndTime": 10,
    "MaxSV": 80
}

###

GET http://localhost:3001/lecturer/profile
Content-Type: application/json

{
    "email": "hainn@soict.hust.edu.vn"
}

###