POST  http://localhost:3001/auth/register
Content-Type: application/json

{
    "email": "messithanh2k@gmail.com",
    "password": "messithanh"
}

###

POST  http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "messithanh2k@gmail.com",
    "password": "messithanh"
}

###

POST http://localhost:3001/student/create
Content-Type: application/json

{
    "FullName": "Nguyen van C",
    "DateOfBirth": "2000-12-12",
    "SchoolYear": 63,
    "Class": "sa",
    "Sex": "Male", 
    "Major": "IT1",
    "Born": "Luong son, hoa binh",
    "IdentityNumber": "114896488",
    "PhoneNumber": "151564856413"
}

###

GET http://localhost:3001/student/11486488
Content-Type: application/json

###


DELETE http://localhost:3001/student/20180012
Content-Type: application/json

###
DELETE http://localhost:3001/auth/delete/20180000@sis.hust.edu.vn
Content-Type: application/json

###
POST http://localhost:3001/student/update
Content-Type: application/json

{
    "SID": "20180002",
    "FullName": "Nguyen van C",
    "DateOfBirth": "2000-12-12",
    "SchoolYear": 63,
    "Class": "01" ,
    "Sex": "Male", 
    "Major": "IT1",
    "Born": "Luong son, hoa binh",
    "IdentityNumber": "114896488",
    "PhoneNumber": "151564856413"
}
###
GET http://localhost:3001/subject/
Content-Type: application/json

###

POST http://localhost:3001/subject/create
Content-Type: application/json

{
    "SubID": "it03",
    "SubName": "avav",
    "Day": "bb",
    "Class": "a" ,
    "StartTime": 6, 
    "EndTime": 10,
    "MaxSV": 80
}

###


GET http://localhost:3001/subject/getStudent/20180001
Content-Type: application/json